spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-db}:${DB_PORT:5432}/${DB_NAME:recipe_prod}
    username: ${DB_USER:recipe_prod_user}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000
      leak-detection-threshold: 10000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: false
    open-in-view: false

logging:
  level:
    root: INFO
    com.github.recipe.app: INFO